### ISSUE TITLE
Error if the_post_thumbnail( array(330, 330) ) is ussed

### ISSUE THREAD

**Issue by holzhannes** [bueltge/multisite-global-media#38]
In my theme `the_post_thumbnail( array(330, 330) )` is ussed I think this gennerates the following error and the page/post is broken.

```
Fatal error: Uncaught TypeError: Argument 4 passed to MultisiteGlobalMedia\postThumbnailHtml() must be of the type string, array given, called in wordpress/wp-includes/class-wp-hook.php on line 286 and defined in wordpress/wp-content/plugins/multisite-global-media-master/multisite-global-media.php:396 Stack trace: #0 wordpress/wp-includes/class-wp-hook.php(286): MultisiteGlobalMedia\postThumbnailHtml('<img width="330...', 141, '25', Array, '') #1 wordpress/wp-includes/plugin.php(203): WP_Hook->apply_filters('<img width="330...', Array) #2 wordpress/wp-includes/post-thumbnail-template.php(179): apply_filters('post_thumbnail_...', '<img width="330...', 141, '25', Array, '') #3 wordpress/wp-includes/post-thumbnail-template.php(62): get_the_post_thumbnail in wordpress/wp-content/plugins/multisite-global-media-master/multisite-global-media.php on line 396
```

**Comment by widoz** [comment]
Hi @holzhannes thanks for reporting this. 

The problem is related with the different type the `$size` parameter can be.
An `array` or `string`. 

The fix is in master but I'd like to have a review by @bueltge

**Comment by bueltge** [comment]
However I'm really happy for testers. So please @holzhannes and other, please test the master and get feedback. Thanks.

**Comment by widoz** [comment]
@bueltge @holzhannes I tested it using the theme 2017 and I don't see any error and the image show up correctly.

![the_post_thumbnail_using_array_for_size_test](https://user-images.githubusercontent.com/1917784/46231164-3735f480-c36b-11e8-8cb4-671776155ac2.png)
